services:
  - type: web
    name: tripnvibe
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_UNSPLASH_ACCESS_KEY
        sync: false
